### ISSUE TITLE
Don't require presence of Analizo binary in collector initialization

### ISSUE THREAD

**Issue by danielkza** [mezuro/kolekti_analizo#7]
Currently the list of metrics is fetched when the collector instance is created. But that means it can't be placed on Rails initializers, or things such as rake tasks will break if Analizo is not available.

We need to make the metric list loading lazy, or change Kolekti to avoid requiring it to be passed as an argument for the `super` constructor.

I found the error while trying to build an updated Prezento package:

```
/usr/share/mezuro/kalibro-processor/vendor/bundle/ruby/2.1.0/bin/rake: No such file or directory - analizo
rake aborted!
Kolekti::CollectorError: Analizo failed with exit status: 127
/usr/share/mezuro/kalibro-processor/vendor/cache/kolekti_analizo-a66fe82a17ff/lib/kolekti_analizo/collector.rb:65:in `metric_list'
/usr/share/mezuro/kalibro-processor/vendor/cache/kolekti_analizo-a66fe82a17ff/lib/kolekti_analizo/collector.rb:42:in `load_analizo_supported_metrics'
/usr/share/mezuro/kalibro-processor/vendor/cache/kolekti_analizo-a66fe82a17ff/lib/kolekti_analizo/collector.rb:11:in `initialize'
```

**Comment by rafamanzo** [comment]
https://github.com/mezuro/kolekti/pull/11 has added an availability check before collector initialization which prevents the issue described here.
